" Minpack load
packadd minpac

call minpac#init()

" minpac must have {'type': 'opt'} so that it can be loaded with `packadd`.
call minpac#add('k-takata/minpac', {'type': 'opt'})
"
" Add other plugins here.
call minpac#add('morhetz/gruvbox')


" Pathogen load
filetype off

call pathogen#infect()
call pathogen#helptags()

set nocompatible
filetype plugin indent on
syntax on
set termguicolors


"make backspace behave in a sane manner
set backspace=indent,eol,start

"print a line under the cursor
set cursorline

"work only in decimal
set nrformats=

"set the ruler
set ruler

"set wildmode(autocompletition)
set wildmode=longest,list,full
set wildmenu

"set vim colorscheme
":colorscheme desert
"set background=light
"silent! colorscheme solarized8
colorscheme gruvbox
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

"disable mouse and bind for enabling  and disabling
if has('mouse')
    set mouse=
    set ttymouse=xterm2
    nnoremap <Leader>m :set mouse=a<CR>
    nnoremap <Leader>M :set mouse=<CR>
endif


"bind \R reload vimrc
nnoremap <Leader>R :source $MYVIMRC<CR>

"display status line always
set laststatus=2

"256 colors
set t_Co=256

"bind \s to save
noremap <Leader>s :update<CR>

"bind \p to paste toggle
set pastetoggle=<Leader>P


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugins
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"enable pymode run and bind it to \r
let g:pymode_run = 1
let g:pymode_run_bind = '<leader>r'
let g:pymode_python = 'python3'

"disable autocomplete documentation
set completeopt=menu

"vim-airline theme
let g:airline_theme="dark"

"bind \p to nerdtree
nnoremap <Leader>p :NERDTreeToggle<CR>

"generate tmux bar airline stile
nnoremap <Leader>t :TmuxlineSnapshot! ~/.tmux/tmuxline.tmux.conf<CR>

"Enable the list of buffers
let g:airline#extensions#tabline#enabled = 1

"Show just the filename
let g:airline#extensions#tabline#fnamemod = ':t'

"vimwiki bind key
:nmap <Leader>wq <Plug>VimwikiVSplitLink
:nmap <Leader>we <Plug>VimwikiSplitLink
